-- sample code 

CREATE OR REPLACE VIEW  sbg_db.sbgiops_br.v_bookings_star 
(  
ADJUSTMENT_TYPE,
	DEAL_ID,
	BUNDLE_PRODUCT_KEY,
	PRODUCT_KEY,
	OFFER_TYPE_NAME,
	RECURRING_OFFER_KEY,
	SALES_ORDER    ) as
  
   (SELECT 
   ADJUSTMENT_TYPE,
	DEAL_ID,
	BUNDLE_PRODUCT_KEY,
	PRODUCT_KEY,
	OFFER_TYPE_NAME,
	RECURRING_OFFER_KEY,
	SALES_ORDER_KEY FROM sbg_db.sbgiops_br.bookings_star  )